config/routes.rb
Rails.application.routes.draw do
  get 'repositories/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root 'repositories#index'
  resources :repositories, only: :index

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/repositories_controller.rb
require 'octokit'

class RepositoriesController < ApplicationController

  def index
    @repositories = params[:search].present? ? search(params[:search]) : []

    respond_to do |format|
      format.html
      format.json { render json: @repositories }
    end
  end

  private

  def search(term)
    Octokit.search_repositories(term).items
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/repositories_helper.rb
module RepositoriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GithubRepos</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
  </head>

  <body class = "container my-5" >
    <%= yield %>
  </body>
</html>

app/views/repositories/_repositories.html.erb
<% @repositories.each do |repository| %>
  <div class="repository card my-3">
    <div class="card-body">
      <h5 class="card-title"><%= link_to repository.name, repository.html_url, target: '_blank' %></h5>
      <p class="card-text"><%= repository.description %></p>
    </div>
  </div>
<% end %>

app/views/repositories/index.html.erb
<%= form_with url: repositories_path, method: :get, data: { controller: 'repositories' }, class: 'd-flex mb-3' do |form| %>
  <%= form.text_field :search, class: 'form-control me-2', placeholder: 'Search repositories...' %>
  <%= form.submit 'Search', class: 'btn btn-primary me-2', data: { action: 'click->repositories#submit' } %>
  <%= button_tag 'Refresh', class: 'btn btn-secondary', type: 'button', data: { action: 'click->repositories#refresh' } %>
<% end %>

<div id="repositories">
  <%= render 'repositories', repositories: @repositories %>
</div>

<%= turbo_frame_tag 'repositories', class: 'mt-3' %>